<div>
    <div class="col-lg-12 grid-margin stretch-card">

        <div class="card">
            <div class="card-body">

                <h4 class="card-title text-primary">
                    Candidate Reports
                </h4>
                <p class="card-description">
                    Download candidate reports.
                </p>

                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Size</th>
                            <th>Mime Type</th>
                            <th>Generated By</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($documents->count())
                            @foreach ($documents as $document)
                                @include('livewire.candidates.includes.document-row', $document)
                            @endforeach
                        @else
                            <tr>
                                <td colspan="6" align="center">
                                    No Records Found.
                                </td>
                            </tr>
                        @endif
                    </tbody>
                </table>

                <br>
                <div class="row">
                    <div class="col">
                        {{ $documents->links() }}
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
